export const getClickUrls = (inputType, convertedType, bbox, z, x, y) => [
  // `https://data.binarix.ru/api/aeggis/v3/${inputType}/wms?REQUEST=GetFeatureInfo&QUERY_LAYERS=${inputType}&SERVICE=WMS&VERSION=1.3.0&FORMAT=image/png&STYLES=&TRANSPARENT=true&LAYERS=${inputType}&RANDOM=${Math.random()}&INFO_FORMAT=application/json&FEATURE_COUNT=10&I=172&J=34&WIDTH=512&HEIGHT=512&CRS=EPSG:3857&BBOX=${bbox}`,
  // `https://data.3witcher.ru/api/aeggis/v3/${inputType}/wms?REQUEST=GetFeatureInfo&QUERY_LAYERS=${inputType}&SERVICE=WMS&VERSION=1.3.0&FORMAT=image/png&STYLES=&TRANSPARENT=true&LAYERS=${inputType}&RANDOM=${Math.random()}&INFO_FORMAT=application/json&FEATURE_COUNT=10&I=172&J=34&WIDTH=512&HEIGHT=512&CRS=EPSG:3857&BBOX=${bbox}`,
  // `https://data.kakrasti.ru/api/aeggis/v3/${inputType}/wms?REQUEST=GetFeatureInfo&QUERY_LAYERS=${inputType}&SERVICE=WMS&VERSION=1.3.0&FORMAT=image/png&STYLES=&TRANSPARENT=true&LAYERS=${inputType}&RANDOM=${Math.random()}&INFO_FORMAT=application/json&FEATURE_COUNT=10&I=172&J=34&WIDTH=512&HEIGHT=512&CRS=EPSG:3857&BBOX=${bbox}`,
  // `https://data.russifiers.ru/api/aeggis/v3/${inputType}/wms?REQUEST=GetFeatureInfo&QUERY_LAYERS=${inputType}&SERVICE=WMS&VERSION=1.3.0&FORMAT=image/png&STYLES=&TRANSPARENT=true&LAYERS=${inputType}&RANDOM=${Math.random()}&INFO_FORMAT=application/json&FEATURE_COUNT=10&I=172&J=34&WIDTH=512&HEIGHT=512&CRS=EPSG:3857&BBOX=${bbox}`,
  // `https://data.inetzar.ru/api/aeggis/v3/${inputType}/wms?REQUEST=GetFeatureInfo&QUERY_LAYERS=${inputType}&SERVICE=WMS&VERSION=1.3.0&FORMAT=image/png&STYLES=&TRANSPARENT=true&LAYERS=${inputType}&RANDOM=${Math.random()}&INFO_FORMAT=application/json&FEATURE_COUNT=10&I=172&J=34&WIDTH=512&HEIGHT=512&CRS=EPSG:3857&BBOX=${bbox}`,
  // `https://data.egrn-online.ru/api/aeggis/v3/${inputType}/wms?REQUEST=GetFeatureInfo&QUERY_LAYERS=${inputType}&SERVICE=WMS&VERSION=1.3.0&FORMAT=image/png&STYLES=&TRANSPARENT=true&LAYERS=${inputType}&RANDOM=${Math.random()}&INFO_FORMAT=application/json&FEATURE_COUNT=10&I=172&J=34&WIDTH=512&HEIGHT=512&CRS=EPSG:3857&BBOX=${bbox}`,
  // `https://data.zhivemtut.online/api/aeggis/v3/${inputType}/wms?REQUEST=GetFeatureInfo&QUERY_LAYERS=${inputType}&SERVICE=WMS&VERSION=1.3.0&FORMAT=image/png&STYLES=&TRANSPARENT=true&LAYERS=${inputType}&RANDOM=${Math.random()}&INFO_FORMAT=application/json&FEATURE_COUNT=10&I=172&J=34&WIDTH=512&HEIGHT=512&CRS=EPSG:3857&BBOX=${bbox}`,
  // `https://data.bigkitty.ru/api/aeggis/v3/${inputType}/wms?REQUEST=GetFeatureInfo&QUERY_LAYERS=${inputType}&SERVICE=WMS&VERSION=1.3.0&FORMAT=image/png&STYLES=&TRANSPARENT=true&LAYERS=${inputType}&RANDOM=${Math.random()}&INFO_FORMAT=application/json&FEATURE_COUNT=10&I=1029&J=104&WIDTH=512&HEIGHT=512&CRS=EPSG:3857&BBOX=${bbox}`,
  `https://pkk.reestrn.ru/api/aeggis/v3/${inputType}/wms?REQUEST=GetFeatureInfo&QUERY_LAYERS=${inputType}&SERVICE=WMS&VERSION=1.3.0&FORMAT=image/png&STYLES=&TRANSPARENT=true&LAYERS=${inputType}&RANDOM=${Math.random()}&INFO_FORMAT=application/json&FEATURE_COUNT=10&I=172&J=34&WIDTH=512&HEIGHT=512&CRS=EPSG:3857&BBOX=${bbox}`,
  // `https://data.gameslog.ru/api/aeggis/v3/${inputType}/wms?REQUEST=GetFeatureInfo&QUERY_LAYERS=${inputType}&SERVICE=WMS&VERSION=1.3.0&FORMAT=image/png&STYLES=&TRANSPARENT=true&LAYERS=${inputType}&RANDOM=${Math.random()}&INFO_FORMAT=application/json&FEATURE_COUNT=10&I=172&J=34&WIDTH=512&HEIGHT=512&CRS=EPSG:3857&BBOX=${bbox}`,
  `https://binep.ru/api/aeggis/v3/${inputType}/wms?REQUEST=GetFeatureInfo&QUERY_LAYERS=${inputType}&SERVICE=WMS&VERSION=1.3.0&FORMAT=image/png&STYLES=&TRANSPARENT=true&LAYERS=${inputType}&RANDOM=${Math.random()}&INFO_FORMAT=application/json&FEATURE_COUNT=10&I=172&J=34&WIDTH=512&HEIGHT=512&CRS=EPSG:3857&BBOX=${bbox}`,
  // `https://data.england-today.ru/api/aeggis/v3/${inputType}/wms?REQUEST=GetFeatureInfo&QUERY_LAYERS=${inputType}&SERVICE=WMS&VERSION=1.3.0&FORMAT=image/png&STYLES=&TRANSPARENT=true&LAYERS=${inputType}&RANDOM=${Math.random()}&INFO_FORMAT=application/json&FEATURE_COUNT=10&I=172&J=34&WIDTH=512&HEIGHT=512&CRS=EPSG:3857&BBOX=${bbox}`,
  // `https://data.androidtalk.ru/api/aeggis/v3/${inputType}/wms?REQUEST=GetFeatureInfo&QUERY_LAYERS=${inputType}&SERVICE=WMS&VERSION=1.3.0&FORMAT=image/png&STYLES=&TRANSPARENT=true&LAYERS=${inputType}&RANDOM=${Math.random()}&INFO_FORMAT=application/json&FEATURE_COUNT=10&I=172&J=34&WIDTH=512&HEIGHT=512&CRS=EPSG:3857&BBOX=${bbox}`,
  // `https://data.motors-vaz.ru/api/aeggis/v3/${inputType}/wms?REQUEST=GetMap&SERVICE=WMS&VERSION=1.3.0&FORMAT=image/png&STYLES=&TRANSPARENT=true&LAYERS=${inputType}&RANDOM=${Math.random()}&WIDTH=512&HEIGHT=512&CRS=EPSG:3857&BBOX=${bbox}`,
  // `https://nspd.gov.ru/api/aeggis/v3/${inputType}/wms?REQUEST=GetFeatureInfo&QUERY_LAYERS=${inputType}&SERVICE=WMS&VERSION=1.3.0&FORMAT=image/png&STYLES=&TRANSPARENT=true&LAYERS=${inputType}&RANDOM=${Math.random()}&INFO_FORMAT=application/json&FEATURE_COUNT=10&I=416&J=271&WIDTH=512&HEIGHT=512&CRS=EPSG:3857&BBOX=${bbox}`,
  // `https://https://data.investstroy33.ru/api/aeggis/v3/${inputType}/wms?REQUEST=GetMap&SERVICE=WMS&VERSION=1.3.0&FORMAT=image/png&STYLES=&TRANSPARENT=true&LAYERS=${inputType}&RANDOM=${Math.random()}&WIDTH=512&HEIGHT=512&CRS=EPSG:3857&BBOX=${bbox}`,
  // `https://data.kotolub.ru/api/aeggis/v3/${inputType}/wms?REQUEST=GetMap&SERVICE=WMS&VERSION=1.3.0&FORMAT=image/png&STYLES=&TRANSPARENT=true&LAYERS=${inputType}&RANDOM=${Math.random()}&WIDTH=512&HEIGHT=512&CRS=EPSG:3857&BBOX=${bbox}`,
  `https://test.fgishub.ru/apipoint.php?point=/api/aeggis/v3/${inputType}/wms&REQUEST=GetFeatureInfo&QUERY_LAYERS=${inputType}&SERVICE=WMS&VERSION=1.3.0&FORMAT=image/png&STYLES=&TRANSPARENT=true&LAYERS=${inputType}&RANDOM=${Math.random()}&INFO_FORMAT=application/json&FEATURE_COUNT=10&I=1122&J=371&WIDTH=1903&HEIGHT=900&CRS=EPSG:3857&BBOX=${bbox}`,
  `https://api.roscadastres.com`,
  `https://binep.ru/api/v3/search`,
  `https://map.ru/api/wms?x=${x}&y=${y}&layers=${inputType}`,
];

export const getTileUrls = (inputType, convertedType, bbox, z, x, y) => [
  // `https://data.binarix.ru/api/aeggis/v3/${inputType}/wms?REQUEST=GetMap&SERVICE=WMS&VERSION=1.3.0&FORMAT=image/png&STYLES=&TRANSPARENT=true&LAYERS=${inputType}&RANDOM=${Math.random()}&WIDTH=512&HEIGHT=512&CRS=EPSG:3857&BBOX=${bbox}`,
  // `https://data.3witcher.ru/api/aeggis/v3/${inputType}/wms?REQUEST=GetMap&SERVICE=WMS&VERSION=1.3.0&FORMAT=image/png&STYLES=&TRANSPARENT=true&LAYERS=${inputType}&RANDOM=${Math.random()}&WIDTH=512&HEIGHT=512&CRS=EPSG:3857&BBOX=${bbox}`,
  // `https://data.kakrasti.ru/api/aeggis/v3/${inputType}/wms?REQUEST=GetMap&SERVICE=WMS&VERSION=1.3.0&FORMAT=image/png&STYLES=&TRANSPARENT=true&LAYERS=${inputType}&RANDOM=${Math.random()}&WIDTH=512&HEIGHT=512&CRS=EPSG:3857&BBOX=${bbox}`,
  `https://pkk.reestr54.ru/tiles/?bbox=${bbox}&layer=${inputType}`,
  `https://api.roscadastres.com/tiles/raster/${z+2}/${x}/${y}.png`,
  // `https://data.zhivemtut.ru/api/aeggis/v3/${inputType}/wms?REQUEST=GetMap&SERVICE=WMS&VERSION=1.3.0&FORMAT=image/png&STYLES=&TRANSPARENT=true&LAYERS=${inputType}&RANDOM=${Math.random()}&WIDTH=512&HEIGHT=512&CRS=EPSG:3857&BBOX=${bbox}`,
  // `https://data.inetzar.ru/api/aeggis/v3/${inputType}/wms?REQUEST=GetMap&SERVICE=WMS&VERSION=1.3.0&FORMAT=image/png&STYLES=&TRANSPARENT=true&LAYERS=${inputType}&RANDOM=${Math.random()}&WIDTH=512&HEIGHT=512&CRS=EPSG:3857&BBOX=${bbox}`,
  // `https://data.egrn-online.ru/api/aeggis/v3/${inputType}/wms?REQUEST=GetMap&SERVICE=WMS&VERSION=1.3.0&FORMAT=image/png&STYLES=&TRANSPARENT=true&LAYERS=${inputType}&RANDOM=${Math.random()}&WIDTH=512&HEIGHT=512&CRS=EPSG:3857&BBOX=${bbox}`,
  // `https://data.russifiers.ru/api/aeggis/v3/${inputType}/wms?REQUEST=GetMap&SERVICE=WMS&VERSION=1.3.0&FORMAT=image/png&STYLES=&TRANSPARENT=true&LAYERS=${inputType}&RANDOM=${Math.random()}&WIDTH=512&HEIGHT=512&CRS=EPSG:3857&BBOX=${bbox}`,
  // `https://data.bigkitty.ru/api/aeggis/v3/${inputType}/wms?REQUEST=GetMap&SERVICE=WMS&VERSION=1.3.0&FORMAT=image/png&STYLES=&TRANSPARENT=true&LAYERS=${inputType}&RANDOM=${Math.random()}&WIDTH=512&HEIGHT=512&CRS=EPSG:3857&BBOX=${bbox}`,
  `https://pkk.reestrn.ru/api/aeggis/v3/${inputType}/wms?REQUEST=GetMap&SERVICE=WMS&VERSION=1.3.0&FORMAT=image/png&STYLES=&TRANSPARENT=true&LAYERS=${inputType}&RANDOM=${Math.random()}&WIDTH=512&HEIGHT=512&CRS=EPSG:3857&BBOX=${bbox}`,
  // `https://data.gameslog.ru/api/aeggis/v3/${inputType}/wms?REQUEST=GetMap&SERVICE=WMS&VERSION=1.3.0&FORMAT=image/png&STYLES=&TRANSPARENT=true&LAYERS=${inputType}&RANDOM=${Math.random()}&WIDTH=512&HEIGHT=512&CRS=EPSG:3857&BBOX=${bbox}`,
  `https://geo.mapbaza.ru/geoserver/postgis/wms?REQUEST=GetMap&SERVICE=WMS&VERSION=1.3.0&FORMAT=image/png&STYLES=&TRANSPARENT=true&LAYERS=postgis:layer_${inputType}&CRS=EPSG:3857&WIDTH=512&HEIGHT=512&BBOX=${bbox}`,
  // `https://data.commix.ru/api/aeggis/v3/${inputType}/wms?REQUEST=GetMap&SERVICE=WMS&VERSION=1.3.0&FORMAT=image/png&STYLES=&TRANSPARENT=true&LAYERS=${inputType}&RANDOM=${Math.random()}&WIDTH=512&HEIGHT=512&CRS=EPSG:3857&BBOX=${bbox}`,
  `https://binep.ru/api/aeggis/v3/${inputType}/wms?service=WMS&request=GetMap&layers=${inputType}&styles=&format=image/png&transparent=true&version=1.3.0&width=512&height=512&RANDOM=${Math.random()}&crs=EPSG:3857&bbox=${bbox}`,
  // `https://data.androidtalk.ru/api/aeggis/v3/${inputType}/wms?REQUEST=GetMap&SERVICE=WMS&VERSION=1.3.0&FORMAT=image/png&STYLES=&TRANSPARENT=true&LAYERS=${inputType}&RANDOM=${Math.random()}&WIDTH=512&HEIGHT=512&CRS=EPSG:3857&BBOX=${bbox}`,
  // `https://data.motors-vaz.ru/api/aeggis/v3/${inputType}/wms?REQUEST=GetMap&SERVICE=WMS&VERSION=1.3.0&FORMAT=image/png&STYLES=&TRANSPARENT=true&LAYERS=${inputType}&RANDOM=${Math.random()}&WIDTH=512&HEIGHT=512&CRS=EPSG:3857&BBOX=${bbox}`,
  `https://nspd.gov.ru/api/aeggis/v3/${inputType}/wms?REQUEST=GetMap&SERVICE=WMS&VERSION=1.3.0&FORMAT=image/png&STYLES=&TRANSPARENT=true&LAYERS=${inputType}&RANDOM=${Math.random()}&WIDTH=512&HEIGHT=512&CRS=EPSG:3857&BBOX=${bbox}`,
  // `https://data.investstroy33.ru/api/aeggis/v3/${inputType}/wms?REQUEST=GetMap&SERVICE=WMS&VERSION=1.3.0&FORMAT=image/png&STYLES=&TRANSPARENT=true&LAYERS=${inputType}&RANDOM=${Math.random()}&WIDTH=512&HEIGHT=512&CRS=EPSG:3857&BBOX=${bbox}`,
  `https://apipkk.ru/api/aeggis/v3/${inputType}/wms?REQUEST=GetMap&SERVICE=WMS&VERSION=1.3.0&FORMAT=image/png&STYLES=&TRANSPARENT=true&LAYERS=${inputType}&RANDOM=${Math.random()}&WIDTH=512&HEIGHT=512&CRS=EPSG:3857&BBOX=${bbox}`,
  // `https://data.england-today.ru/api/aeggis/v3/${inputType}/wms?REQUEST=GetMap&SERVICE=WMS&VERSION=1.3.0&FORMAT=image/png&STYLES=&TRANSPARENT=true&LAYERS=${inputType}&RANDOM=${Math.random()}&WIDTH=512&HEIGHT=512&CRS=EPSG:3857&BBOX=${bbox}`,
  // `https://data.kotolub.ru/api/aeggis/v3/${inputType}/wms?REQUEST=GetMap&SERVICE=WMS&VERSION=1.3.0&FORMAT=image/png&STYLES=&TRANSPARENT=true&LAYERS=${inputType}&RANDOM=${Math.random()}&WIDTH=512&HEIGHT=512&CRS=EPSG:3857&BBOX=${bbox}`,
];

export const getGeoportalUrls = (cadNum) => [
  // `https://data.3witcher.ru/api/geoportal/v2/search/geoportal?query=${cadNum}`,
  // `https://data.binarix.ru/api/geoportal/v2/search/geoportal?query=${cadNum}`,
  // `https://data.zhivemtut.ru/api/geoportal/v2/search/geoportal?query=${cadNum}`,
  // `https://data.inetzar.ru/api/geoportal/v2/search/geoportal?query=${cadNum}`,
  // `https://data.bigkitty.ru/api/geoportal/v2/search/geoportal?query=${cadNum}`,
  // `https://data.egrn-online.ru/api/geoportal/v2/search/geoportal?query=${cadNum}`,
  // `https://data.gameslog.ru/api/geoportal/v2/search/geoportal?query=${cadNum}`,
  // `https://data.russifiers.ru/api/geoportal/v2/search/geoportal?query=${cadNum}`,
  // `https://data.kakrasti.ru/api/geoportal/v2/search/geoportal?query=${cadNum}`,
  // `https://data.motors-vaz.ru/api/geoportal/v2/search/geoportal?query=${cadNum}`,
  // `https://data.investstroy33.ru/api/geoportal/v2/search/geoportal?query=${cadNum}`,
  `https://ns2.mapbaza.ru/api/geoportal/v2/search/geoportal?query=${cadNum}`,
  `https://nspd.gov.ru/api/geoportal/v2/search/cadastralPrice?query=${cadNum}`,
  `https://nspd.gov.ru/api/geoportal/v2/search/geoportal?query=${cadNum}`,
  'https://binep.ru/api/v3/search',
  `https://test.fgishub.ru/api.php?query=${cadNum}`,
  `https://map.ru/api/kad/suggestions?query=${cadNum}`,
  `https://api.roscadastres.com/pkk_files/data2.php?type=5&id=${cadNum}`,
  `https://nspd.gov.ru/api/data-fund/v1/geom?kind=land&cadNumber=${cadNum}`,
  `https://pkk.reestrn.ru/api/geoportal/v2/search/geoportal?query=${cadNum}`,
];

export const getHistoryUrls = (cadNum) => [
  // `https://data.3witcher.ru/api/data-fund/v2/cadastral-history-diagram?cadNumber=${cadNum}`,
  // `https://data.binarix.ru/api/api/data-fund/v2/cadastral-history-diagram?cadNumber=${cadNum}`,
  // `https://data.bigkitty.ru/api/data-fund/v2/cadastral-history-diagram?cadNumber=${cadNum}`,
  // `https://data.egrn-online.ru/api/data-fund/v2/cadastral-history-diagram?cadNumber=${cadNum}`,
  // `https://data.inetzar.ru/api/data-fund/v2/cadastral-history-diagram?cadNumber=${cadNum}`,
  // `https://data.zhivemtut.ru/api/data-fund/v2/cadastral-history-diagram?cadNumber=${cadNum}`,
  // `https://pkk.reestrn.ru/api/api/data-fund/v2/cadastral-history-diagram?cadNumber=${cadNum}`,
  // `https://data.gameslog.ru/api/data-fund/v2/cadastral-history-diagram?cadNumber=${cadNum}`,
  // `https://data.russifiers.ru/api/data-fund/v2/cadastral-history-diagram?cadNumber=${cadNum}`,
  // `https://data.kakrasti.ru/api/data-fund/v2/cadastral-history-diagram?cadNumber=${cadNum}`,
  // `https://data.commix.ru/api/data-fund/v2/cadastral-history-diagram?cadNumber=${cadNum}`,
  // `https://binep.ru/api/data-fund/v2/cadastral-history-diagram?cadNumber=${cadNum}`,
  // `https://data.england-today.ru/api/data-fund/v2/cadastral-history-diagram?cadNumber=${cadNum}`,
  // `https://data.motors-vaz.ru/api/data-fund/v2/cadastral-history-diagram?cadNumber=${cadNum}`,
  // `https://data.investstroy33.ru/api/data-fund/v2/cadastral-history-diagram?cadNumber=${cadNum}`,
  `https://apipkk.ru/api/data-fund/v2/cadastral-history-diagram?cadNumber=${cadNum}`,
  `https://nspd.gov.ru/api/data-fund/v2/cadastral-history-diagram?cadNumber=${cadNum}`,

];


 export const origins = [
    "https://pkk-egrp365.ru",
    "https://nspd-rosreestr.ru",
    "https://egrp-rosreestr.ru",
    "https://rosreestr-pkk.ru",
    "https://pkk5-rosreestor.ru",
    "https://egrp365-karta.ru",
    "https://rosreestr-russia.ru",
    "https://ppk5-rosreestra.ru",
    "http://rosreestr-egrp.ru/",
    "https://ppk5.ru/",
  ];

